# Generated by Django 4.1.3 on 2022-11-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.CharField(default='2022-11-13 07:12:32', max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=150),
        ),
    ]
