# Generated by Django 4.1.3 on 2022-11-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_start_date_alter_newuser_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.CharField(default='2022-11-14 16:51:05', max_length=100),
        ),
    ]
