# Generated by Django 4.1.3 on 2022-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='start_date',
            field=models.CharField(default='2022-11-15 09:20:44', max_length=100),
        ),
    ]
