# Generated by Django 4.1.3 on 2022-11-15 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=5000)),
                ('question_number', models.IntegerField(default=-1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='QuizMainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type_number', models.IntegerField(default=-1)),
                ('question_type', models.CharField(max_length=100)),
                ('listeningmp3file', models.CharField(default='', max_length=1000)),
                ('question', models.CharField(max_length=5000)),
                ('question_body', models.CharField(max_length=5000000)),
                ('question_element_num', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='QuizRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_img', models.CharField(default='', max_length=1000)),
                ('quiz_room_title', models.CharField(max_length=500)),
                ('about_quiz_room', models.CharField(max_length=5000)),
                ('created_at', models.CharField(default='2022-11-15 09:18:51', max_length=100)),
                ('modified_at', models.CharField(default='2022-11-15 09:18:51', max_length=100)),
                ('timer', models.IntegerField(default=0)),
                ('question_type_and_question_num', models.JSONField(default=list)),
                ('participants_list', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestionModel',
            fields=[
                ('questionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizapp.questionmodel')),
                ('choices_num', models.IntegerField(default=-1)),
                ('choice_problems', models.JSONField(default=dict)),
                ('answer_choice', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('quizapp.questionmodel',),
        ),
        migrations.CreateModel(
            name='NarrativeQuestionModel',
            fields=[
                ('questionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizapp.questionmodel')),
                ('answer_keywords', models.JSONField(default=list)),
                ('best_answer', models.CharField(default='', max_length=10000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('quizapp.questionmodel',),
        ),
        migrations.CreateModel(
            name='ShortAnswerQuestionModel',
            fields=[
                ('questionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quizapp.questionmodel')),
                ('answer_word', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('quizapp.questionmodel',),
        ),
        migrations.CreateModel(
            name='StudentQuizModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.JSONField(default=list)),
                ('real_answer', models.JSONField(default=list)),
                ('score_percentage', models.IntegerField(default=0)),
                ('correct_list', models.JSONField(default=list)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_quiz_model', to='quizapp.quizroommodel')),
            ],
        ),
    ]
