# Generated by Django 4.1.3 on 2022-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_quizroommodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizroommodel',
            name='created_at',
            field=models.CharField(default='2022-11-15 09:20:44', max_length=100),
        ),
        migrations.AlterField(
            model_name='quizroommodel',
            name='modified_at',
            field=models.CharField(default='2022-11-15 09:20:44', max_length=100),
        ),
    ]
