# Generated by Django 4.1.3 on 2022-11-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('modified_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('actual_rsrc_txt', models.CharField(max_length=1000000000)),
                ('memo_html', models.CharField(max_length=1000000000)),
                ('highlight_html', models.CharField(max_length=1000000000)),
                ('tags', models.JSONField(default=list)),
                ('participants', models.JSONField(default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingVocabModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True)),
                ('meaning_kor', models.CharField(max_length=100)),
                ('meaning_en', models.CharField(max_length=100)),
                ('synonym', models.CharField(max_length=100)),
                ('antonym', models.CharField(max_length=100)),
                ('example_sen', models.CharField(max_length=100)),
                ('pronunciation', models.CharField(max_length=100)),
                ('color', models.CharField(default='노랑색', max_length=20)),
                ('target_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_vocab_model', to='readingapp.readingdatamodel')),
            ],
        ),
    ]
