# Generated by Django 4.1.3 on 2022-11-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingdatamodel',
            name='created_at',
            field=models.CharField(default='2022-11-13 07:12:32', max_length=100),
        ),
        migrations.AlterField(
            model_name='readingdatamodel',
            name='modified_at',
            field=models.CharField(default='2022-11-13 07:12:32', max_length=100),
        ),
    ]
