# Generated by Django 4.1.3 on 2022-11-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readingapp', '0003_alter_readingdatamodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingdatamodel',
            name='created_at',
            field=models.CharField(default='2022-11-14 16:51:05', max_length=100),
        ),
        migrations.AlterField(
            model_name='readingdatamodel',
            name='modified_at',
            field=models.CharField(default='2022-11-14 16:51:05', max_length=100),
        ),
    ]
