# Generated by Django 4.1.3 on 2022-11-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningBlankSheetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_score_list', models.JSONField(default=list)),
                ('blank_word_and_id', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_file_name', models.JSONField(default=dict)),
                ('script_text', models.CharField(max_length=100000000000000)),
                ('created_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('modified_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
