# Generated by Django 4.1.3 on 2022-11-15 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_file_name', models.JSONField(default=dict)),
                ('script_text', models.CharField(max_length=100000)),
                ('created_at', models.CharField(default='2022-11-15 09:19:33', max_length=100)),
                ('modified_at', models.CharField(default='2022-11-15 09:19:33', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_data_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListeningBlankSheetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_score_list', models.JSONField(default=list)),
                ('blank_word_and_id', models.JSONField(default=dict)),
                ('target_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listeningapp.listeningdatamodel')),
            ],
        ),
    ]
