# Generated by Django 4.1.3 on 2022-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listeningapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningdatamodel',
            name='created_at',
            field=models.CharField(default='2022-11-15 09:20:18', max_length=100),
        ),
        migrations.AlterField(
            model_name='listeningdatamodel',
            name='modified_at',
            field=models.CharField(default='2022-11-15 09:20:18', max_length=100),
        ),
    ]
