# Generated by Django 4.1.3 on 2022-11-15 00:18

from django.db import migrations, models
import mypage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_data', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfileInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img_file_names', models.JSONField(blank=True, default=mypage.models.default_set_profile_img_file_names)),
                ('bg_img_file_names', models.JSONField(default=mypage.models.default_set_bg_img_file_names)),
                ('current_profile_img', models.CharField(default='default/user.png', max_length=100)),
                ('current_bg_img', models.CharField(default='default/wallpaper.jpg', max_length=100)),
                ('about_hash_tags', models.JSONField(blank=True, default=list)),
                ('friends_list', models.JSONField(blank=True, default=list)),
                ('friends_data', models.JSONField(default=mypage.models.default_set_friends_data)),
                ('followers', models.JSONField(blank=True, default=list)),
                ('followings', models.JSONField(blank=True, default=list)),
                ('liking', models.JSONField(blank=True, default=list)),
                ('liked', models.JSONField(blank=True, default=list)),
                ('inbox', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
