# Generated by Django 4.1.3 on 2022-11-15 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=1000)),
                ('meaning_kor', models.CharField(blank=True, default='', max_length=1000)),
                ('meaning_kor_keywords', models.JSONField(default=list)),
                ('meaning_en', models.CharField(blank=True, default='', max_length=3000)),
                ('meaning_en_keywords', models.JSONField(default=list)),
                ('synonym', models.CharField(blank=True, default='', max_length=1000)),
                ('antonym', models.CharField(blank=True, default='', max_length=1000)),
                ('example_sen', models.CharField(blank=True, default='', max_length=1000)),
                ('pronunciation', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='노랑색', max_length=20)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_quiz', to='vocabapp.vocabnote')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='VocabQuizType1',
            fields=[
                ('vocabquiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vocabapp.vocabquiz')),
                ('ans_keywords', models.JSONField(default=list)),
                ('user_ans_words', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vocabapp.vocabquiz',),
        ),
        migrations.CreateModel(
            name='VocabQuizType2',
            fields=[
                ('vocabquiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vocabapp.vocabquiz')),
                ('ans', models.JSONField(default=list)),
                ('user_ans', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vocabapp.vocabquiz',),
        ),
        migrations.CreateModel(
            name='VocabQuizType3',
            fields=[
                ('vocabquiz_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vocabapp.vocabquiz')),
                ('kor_ans', models.CharField(max_length=1000)),
                ('ans_keyword', models.CharField(default='', max_length=1000)),
                ('en_ans', models.CharField(max_length=1000)),
                ('user_ans', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('vocabapp.vocabquiz',),
        ),
        migrations.CreateModel(
            name='RequestUserVocabRandomQuizIdList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_list', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
