# Generated by Django 4.1.3 on 2022-11-12 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_actual_rsrc_text', models.CharField(default='', max_length=100000000)),
                ('highlight_html', models.CharField(max_length=100000000000)),
                ('memo_html', models.CharField(max_length=100000000000)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('evaluation_text', models.CharField(max_length=100000000)),
                ('created_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('modified_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_model', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='WritingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.CharField(max_length=100)),
                ('participated_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('editor_list', models.JSONField(default=list)),
                ('my_writing_topic', models.CharField(default='', max_length=100000)),
                ('my_writing_content', models.CharField(default='', max_length=100000000)),
                ('comment_list', models.JSONField(default=list)),
                ('created_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('modified_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='WritingRoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default='2022-11-13 07:11:50', max_length=100)),
                ('participants', models.JSONField(default=list)),
                ('topic', models.CharField(max_length=100000)),
                ('about_content', models.CharField(max_length=100000)),
                ('about_room', models.CharField(max_length=100000)),
                ('room_title', models.CharField(max_length=100000)),
                ('hash', models.CharField(default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_room_model', to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='BookRoomModel',
            fields=[
                ('writingroommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writingapp.writingroommodel')),
                ('book_info', models.CharField(max_length=100000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('writingapp.writingroommodel',),
        ),
        migrations.CreateModel(
            name='EssayRoomModel',
            fields=[
                ('writingroommodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writingapp.writingroommodel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('writingapp.writingroommodel',),
        ),
        migrations.CreateModel(
            name='EssayModel',
            fields=[
                ('writingmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writingapp.writingmodel')),
                ('essay_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_participant_model', to='writingapp.essayroommodel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('writingapp.writingmodel',),
        ),
        migrations.CreateModel(
            name='EssayEditorModel',
            fields=[
                ('editormodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writingapp.editormodel')),
                ('essay_model_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_editor_model_target', to='writingapp.essaymodel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('writingapp.editormodel',),
        ),
        migrations.CreateModel(
            name='BookWritingModel',
            fields=[
                ('writingmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writingapp.writingmodel')),
                ('book_progress', models.FloatField(default=0)),
                ('book_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_writing_participant_model', to='writingapp.bookroommodel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('writingapp.writingmodel',),
        ),
        migrations.CreateModel(
            name='BookWritingEditorModel',
            fields=[
                ('editormodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='writingapp.editormodel')),
                ('book_writing_model_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_writing_editor_model_target', to='writingapp.bookwritingmodel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('writingapp.editormodel',),
        ),
    ]
