# Generated by Django 4.1.3 on 2022-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editormodel',
            name='created_at',
            field=models.CharField(default='2022-11-15 09:19:33', max_length=100),
        ),
        migrations.AlterField(
            model_name='editormodel',
            name='modified_at',
            field=models.CharField(default='2022-11-15 09:19:33', max_length=100),
        ),
        migrations.AlterField(
            model_name='writingmodel',
            name='created_at',
            field=models.CharField(default='2022-11-15 09:19:33', max_length=100),
        ),
        migrations.AlterField(
            model_name='writingmodel',
            name='modified_at',
            field=models.CharField(default='2022-11-15 09:19:33', max_length=100),
        ),
        migrations.AlterField(
            model_name='writingmodel',
            name='participated_at',
            field=models.CharField(default='2022-11-15 09:19:33', max_length=100),
        ),
        migrations.AlterField(
            model_name='writingroommodel',
            name='created_at',
            field=models.CharField(default='2022-11-15 09:19:33', max_length=100),
        ),
    ]
